/**
 * Rendering `wrangler.jsonc`.
 *
 * The file is regenerated from settings rather than patched in place. Patching
 * would mean parsing JSON-with-comments, editing an AST, and re-emitting it
 * while preserving every comment — a large amount of machinery whose failure
 * mode is a silently mangled deployment config. Regenerating is deterministic:
 * the same settings always produce the same bytes, so a re-run is a no-op, and
 * an author who edited the file by hand gets the ordinary
 * confirm-and-back-up path from `Actions.writeFile` rather than a surprise.
 */

export interface CollaborationSettings {
  /** D1 database name and id from `wrangler d1 create`. */
  readonly d1Name: string;
  readonly d1Id: string;
  readonly projectSlug: string;
  /** `owner/repo`. */
  readonly projectRepo: string;
  /** GitHub login of the author, seeded as the first maintainer. */
  readonly maintainerLogin: string;
  readonly defaultBranch: string;
  /** GitHub App client id — public, so it lives in vars rather than secrets. */
  readonly githubClientId: string;
  /** Absolute callback URL on the site's own origin (ADR-0019). */
  readonly redirectUri: string;
  /** GitHub App installation id. */
  readonly installationId: string;
  /** Base path when the book is served under a subpath, e.g. `/my-book`. */
  readonly basePath?: string;
}

export interface WranglerSettings {
  readonly workerName: string;
  readonly compatibilityDate?: string;
  /** Custom domain, e.g. `book.example.com`. */
  readonly customDomain?: string;
  readonly collaboration?: CollaborationSettings;
}

const DEFAULT_COMPATIBILITY_DATE = "2026-06-01";

function json(value: string): string {
  return JSON.stringify(value);
}

export function renderWrangler(settings: WranglerSettings): string {
  const compatibilityDate = settings.compatibilityDate ?? DEFAULT_COMPATIBILITY_DATE;
  const header = `// Cloudflare Worker configuration for this book (ADR-0020: GitHub for the
// repository, Cloudflare for hosting — there is no second supported host).
//
// GENERATED BY create-authorbot. Editing it by hand is fine; the wizard will
// ask before replacing anything you changed, and keeps a backup when it does.
//
// \`name\` is the identity of the Worker your CI deploys to and part of your
// default URL. Renaming it creates a *second* Worker rather than moving this
// one, so the old URL keeps serving the old book.
//
// NO SECRETS IN THIS FILE. The token that lets CI deploy is a GitHub
// repository secret; anything the Worker itself needs is set with
// \`wrangler secret put\`, which never writes to disk.
//
// DEPLOY FROM CI, NOT FROM YOUR LAPTOP. \`_site\` is build output; a local
// \`wrangler deploy\` publishes whatever happens to be in that directory, and a
// stale one quietly replaces your live book with an older version.`;

  const lines: string[] = [header, "{"];
  lines.push(`  "name": ${json(settings.workerName)},`);

  if (settings.collaboration !== undefined) {
    lines.push(
      "",
      "  // Same-origin by design (ADR-0019): this one Worker serves the built",
      "  // site AND the collaboration API at /v1/*, so there is no CORS, no",
      "  // cookie relaxation, and no second URL. A request that matches a built",
      "  // asset never reaches the API code, so an API fault cannot take your",
      "  // prose offline.",
      "  //",
      "  // Nothing here is compiled from source (ADR-0022): `main` names a",
      "  // prebuilt Worker inside node_modules, and `migrations_dir` names the",
      "  // SQL that shipped with that same version — so your database schema and",
      "  // your Worker code can never be different releases.",
      `  "main": "node_modules/@authorbot/api/dist/worker.js",`,
      `  "compatibility_flags": ["nodejs_compat"],`,
      "  // @authorbot/database also re-exports a native SQLite adapter used by",
      "  // the toolchain's own tests. The Worker never calls it — it uses the D1",
      "  // binding — so it is aliased to a stub that throws, keeping a native",
      "  // module out of the bundle.",
      `  "alias": {`,
      `    "better-sqlite3": "./node_modules/@authorbot/api/dist/stubs/better-sqlite3.js"`,
      `  },`,
    );
  }

  lines.push(`  "compatibility_date": ${json(compatibilityDate)},`);

  if (settings.customDomain !== undefined && settings.customDomain.length > 0) {
    lines.push(
      "",
      "  // Custom domain. Cloudflare must already be authoritative for this",
      "  // zone; the workers.dev address keeps working alongside it.",
      `  "routes": [{ "pattern": ${json(settings.customDomain)}, "custom_domain": true }],`,
    );
  }

  if (settings.collaboration !== undefined) {
    const c = settings.collaboration;
    lines.push(
      "",
      `  "d1_databases": [`,
      `    {`,
      `      "binding": "DB",`,
      `      "database_name": ${json(c.d1Name)},`,
      `      "database_id": ${json(c.d1Id)},`,
      `      "migrations_dir": "node_modules/@authorbot/api/migrations"`,
      `    }`,
      `  ],`,
      "  // The coordinator is the single writer for anything that touches Git:",
      "  // one commit per logical change, no races between concurrent requests.",
      `  "durable_objects": {`,
      `    "bindings": [{ "name": "COORDINATOR", "class_name": "ProjectCoordinator" }]`,
      `  },`,
      `  "migrations": [{ "tag": "v1", "new_sqlite_classes": ["ProjectCoordinator"] }],`,
      "  // Drains the outbox and sweeps expired leases once a minute.",
      `  "triggers": { "crons": ["* * * * *"] },`,
      `  "vars": {`,
      `    "AUTH_MODE": "github",`,
      `    "MIRROR_MODE": "durable",`,
      `    "PROJECT_SLUG": ${json(c.projectSlug)},`,
      `    "PROJECT_REPO": ${json(c.projectRepo)},`,
      `    "INITIAL_MAINTAINER": ${json(`github:${c.maintainerLogin}`)},`,
      `    "DEFAULT_BRANCH": ${json(c.defaultBranch)},`,
      "    // The client id is public; the client secret, the private key, the",
      "    // webhook secret, and SESSION_SECRET are set with `wrangler secret put`",
      "    // and never appear in this file.",
      `    "GITHUB_CLIENT_ID": ${json(c.githubClientId)},`,
      `    "GITHUB_REDIRECT_URI": ${json(c.redirectUri)},`,
      `    "GITHUB_INSTALLATION_ID": ${json(c.installationId)}${
        c.basePath === undefined || c.basePath === "" ? "" : ","
      }`,
    );
    if (c.basePath !== undefined && c.basePath !== "") {
      lines.push(
        "    // Serving under a subpath (ADR-0019 §6). Must stay identical to",
        "    // `publication.api_url` in book.yml.",
        `    "API_BASE_PATH": ${json(c.basePath)}`,
      );
    }
    lines.push(`  },`);
  }

  lines.push(`  "assets": {`, `    "directory": "./_site"`, `  }`, "}", "");
  return lines.join("\n");
}
