-- Migration 0001: Phase 2 identity and collaboration records.
-- Phase 2 contract §2; design §9.2 subset. One SQLite dialect for both
-- Cloudflare D1 (production, applied via `wrangler d1 migrations apply`)
-- and better-sqlite3 (tests/local dev, applied via the Node runner in
-- @authorbot/database).
--
-- Conventions: UUIDv7 TEXT primary keys generated by callers; RFC 3339 UTC
-- TEXT timestamps; JSON payloads stored as TEXT. Token and session secrets
-- are stored as SHA-256 hashes only — no plaintext column exists.

CREATE TABLE projects (
  id                    TEXT PRIMARY KEY,
  slug                  TEXT NOT NULL,
  repo_provider         TEXT NOT NULL DEFAULT 'github',
  repo                  TEXT NOT NULL,
  default_branch        TEXT NOT NULL DEFAULT 'main',
  status                TEXT NOT NULL DEFAULT 'active',
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

CREATE UNIQUE INDEX idx_projects_slug ON projects (slug);

CREATE TABLE actors (
  id                    TEXT PRIMARY KEY,
  type                  TEXT NOT NULL CHECK (type IN ('human', 'agent', 'system')),
  display_name          TEXT NOT NULL,
  external_identity     TEXT,
  owner_actor_id        TEXT REFERENCES actors (id),
  status                TEXT NOT NULL DEFAULT 'active',
  created_at            TEXT NOT NULL
);

CREATE UNIQUE INDEX idx_actors_external_identity
  ON actors (external_identity)
  WHERE external_identity IS NOT NULL;

CREATE TABLE project_memberships (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  actor_id              TEXT NOT NULL REFERENCES actors (id),
  role                  TEXT NOT NULL
    CHECK (role IN ('reader', 'contributor', 'editor', 'maintainer')),
  scopes                TEXT NOT NULL,
  created_at            TEXT NOT NULL,
  revoked_at            TEXT
);

-- Contract §2: unique (project_id, actor_id) membership.
CREATE UNIQUE INDEX idx_project_memberships_project_actor
  ON project_memberships (project_id, actor_id);

CREATE TABLE human_sessions (
  id                    TEXT PRIMARY KEY,
  session_hash          TEXT NOT NULL,
  actor_id              TEXT NOT NULL REFERENCES actors (id),
  created_at            TEXT NOT NULL,
  expires_at            TEXT NOT NULL,
  revoked_at            TEXT
);

CREATE UNIQUE INDEX idx_human_sessions_hash ON human_sessions (session_hash);

CREATE TABLE agent_tokens (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  actor_id              TEXT NOT NULL REFERENCES actors (id),
  name                  TEXT NOT NULL,
  token_hash            TEXT NOT NULL,
  scopes                TEXT NOT NULL,
  created_by            TEXT NOT NULL REFERENCES actors (id),
  created_at            TEXT NOT NULL,
  expires_at            TEXT NOT NULL,
  revoked_at            TEXT,
  last_used_at          TEXT
);

-- Contract §2: unique agent-token hash.
CREATE UNIQUE INDEX idx_agent_tokens_hash ON agent_tokens (token_hash);

CREATE TABLE chapters (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  path                  TEXT NOT NULL,
  slug                  TEXT NOT NULL,
  title                 TEXT NOT NULL,
  status                TEXT NOT NULL
    CHECK (status IN ('draft', 'proposed', 'published', 'archived')),
  revision              INTEGER NOT NULL CHECK (revision >= 1),
  content_hash          TEXT NOT NULL,
  head_commit           TEXT,
  last_published_commit TEXT,
  -- JSON array of the valid block-marker ids in this projected revision.
  -- Persisted so contract §4's "blockId exists in that revision" check works
  -- from the database alone (e.g. a reader-less instance sharing the DB).
  block_ids             TEXT NOT NULL DEFAULT '[]',
  updated_at            TEXT NOT NULL
);

CREATE UNIQUE INDEX idx_chapters_project_slug ON chapters (project_id, slug);
CREATE UNIQUE INDEX idx_chapters_project_path ON chapters (project_id, path);

CREATE TABLE git_operations (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  correlation_id        TEXT NOT NULL,
  expected_head         TEXT,
  state                 TEXT NOT NULL DEFAULT 'queued'
    CHECK (state IN ('queued', 'preparing', 'committing', 'committed',
                     'verified', 'conflict', 'failed')),
  attempts              INTEGER NOT NULL DEFAULT 0,
  commit_sha            TEXT,
  error                 TEXT,
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

CREATE INDEX idx_git_operations_project_state ON git_operations (project_id, state);

CREATE TABLE annotations (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  -- Deliberately NOT a foreign key to chapters: annotations can outlive their
  -- chapter (Phase 0 status vocabulary `orphaned`), and projection rebuilds
  -- replace chapter rows while preserving operational annotation rows
  -- (`pending_git` / `orphaned`) in place.
  chapter_id            TEXT NOT NULL,
  kind                  TEXT NOT NULL CHECK (kind IN ('comment', 'suggestion')),
  scope                 TEXT NOT NULL CHECK (scope IN ('range', 'block', 'chapter')),
  chapter_revision      INTEGER NOT NULL CHECK (chapter_revision >= 1),
  target                TEXT,
  author_actor_id       TEXT NOT NULL REFERENCES actors (id),
  body                  TEXT NOT NULL,
  status                TEXT NOT NULL DEFAULT 'pending_git'
    CHECK (status IN ('pending_git', 'open', 'work_item_created', 'accepted',
                      'resolved', 'rejected', 'withdrawn', 'superseded',
                      'orphaned', 'needs_reanchor')),
  git_operation_id      TEXT REFERENCES git_operations (id),
  superseded_by         TEXT,
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

CREATE INDEX idx_annotations_chapter ON annotations (chapter_id, created_at);

CREATE TABLE replies (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  annotation_id         TEXT NOT NULL REFERENCES annotations (id),
  parent_reply_id       TEXT REFERENCES replies (id),
  author_actor_id       TEXT NOT NULL REFERENCES actors (id),
  body                  TEXT NOT NULL,
  status                TEXT NOT NULL DEFAULT 'pending_git'
    CHECK (status IN ('pending_git', 'open', 'withdrawn')),
  git_operation_id      TEXT REFERENCES git_operations (id),
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

CREATE INDEX idx_replies_annotation ON replies (annotation_id, created_at);

CREATE TABLE outbox (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  git_operation_id      TEXT REFERENCES git_operations (id),
  kind                  TEXT NOT NULL,
  payload               TEXT NOT NULL,
  status                TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'done', 'failed')),
  attempts              INTEGER NOT NULL DEFAULT 0,
  created_at            TEXT NOT NULL,
  processed_at          TEXT
);

CREATE INDEX idx_outbox_project_status ON outbox (project_id, status, created_at);

CREATE TABLE idempotency_keys (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  actor_id              TEXT NOT NULL REFERENCES actors (id),
  key                   TEXT NOT NULL,
  request_hash          TEXT NOT NULL,
  response_status       INTEGER,
  response_body         TEXT,
  created_at            TEXT NOT NULL
);

-- Contract §2: unique idempotency (project_id, actor_id, key).
CREATE UNIQUE INDEX idx_idempotency_keys_scope
  ON idempotency_keys (project_id, actor_id, key);

CREATE TABLE webhook_deliveries (
  id                    TEXT PRIMARY KEY,
  delivery_id           TEXT NOT NULL,
  event                 TEXT NOT NULL,
  status                TEXT NOT NULL DEFAULT 'received'
    CHECK (status IN ('received', 'processed', 'ignored', 'failed')),
  received_at           TEXT NOT NULL,
  processed_at          TEXT
);

-- Contract §2: unique webhook delivery id.
CREATE UNIQUE INDEX idx_webhook_deliveries_delivery_id
  ON webhook_deliveries (delivery_id);

CREATE TABLE audit_events (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  actor_id              TEXT REFERENCES actors (id),
  action                TEXT NOT NULL,
  target_type           TEXT NOT NULL,
  target_id             TEXT,
  correlation_id        TEXT NOT NULL,
  metadata              TEXT,
  created_at            TEXT NOT NULL
);

CREATE INDEX idx_audit_events_project ON audit_events (project_id, created_at);

-- Contract §2: audit_events is append-only. Enforced in-schema via triggers.
CREATE TRIGGER audit_events_no_update
BEFORE UPDATE ON audit_events
BEGIN
  SELECT RAISE(ABORT, 'audit_events is append-only');
END;

CREATE TRIGGER audit_events_no_delete
BEFORE DELETE ON audit_events
BEGIN
  SELECT RAISE(ABORT, 'audit_events is append-only');
END;
