-- Migration 0002: Phase 3 votes, decisions, work items, and the event feed.
-- Phase 3 contract §2, §4, §5; design §11, §13, §15.5. Same single SQLite
-- dialect for Cloudflare D1 (production) and better-sqlite3 (tests/local).
--
-- Conventions follow 0001: UUIDv7 TEXT primary keys generated by callers
-- (except `events`, whose id is an AUTOINCREMENT integer — the SSE cursor);
-- RFC 3339 UTC TEXT timestamps; JSON payloads stored as TEXT.

-- Contract §2: one current vote per (annotation, actor); upsert on change.
CREATE TABLE votes (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  annotation_id         TEXT NOT NULL REFERENCES annotations (id),
  actor_id              TEXT NOT NULL REFERENCES actors (id),
  value                 TEXT NOT NULL CHECK (value IN ('approve', 'reject', 'abstain')),
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

-- Contract §2: THE one-current-vote constraint.
CREATE UNIQUE INDEX idx_votes_annotation_actor ON votes (annotation_id, actor_id);

-- Contract §2: append-only history of vote changes. `value` NULL records a
-- cleared vote (DELETE); `previous_value` NULL records a first vote.
CREATE TABLE vote_events (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  annotation_id         TEXT NOT NULL REFERENCES annotations (id),
  actor_id              TEXT NOT NULL REFERENCES actors (id),
  value                 TEXT CHECK (value IN ('approve', 'reject', 'abstain')),
  previous_value        TEXT CHECK (previous_value IN ('approve', 'reject', 'abstain')),
  created_at            TEXT NOT NULL
);

CREATE INDEX idx_vote_events_annotation ON vote_events (annotation_id, id);

-- vote_events is append-only. Enforced in-schema via triggers (same pattern
-- as audit_events in 0001).
CREATE TRIGGER vote_events_no_update
BEFORE UPDATE ON vote_events
BEGIN
  SELECT RAISE(ABORT, 'vote_events is append-only');
END;

CREATE TRIGGER vote_events_no_delete
BEFORE DELETE ON vote_events
BEGIN
  SELECT RAISE(ABORT, 'vote_events is append-only');
END;

-- Contract §4 / design §11.3–11.4: sticky decision records. Deliberately NOT
-- a foreign key to annotations: decisions are rebuilt from committed
-- `.authorbot/decisions/<id>.yml` artifacts and must survive projection
-- rebuilds that replace annotation rows (same rationale as
-- annotations.chapter_id in 0001).
CREATE TABLE decisions (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  source_annotation_id  TEXT NOT NULL,
  action_type           TEXT NOT NULL,
  rule                  TEXT NOT NULL,
  -- rule_version 0 is reserved for maintainer force-create (contract §4).
  rule_version          INTEGER NOT NULL CHECK (rule_version >= 0),
  -- Aggregate metrics snapshot at threshold crossing (JSON object of
  -- numbers). Aggregates only — never per-voter data (design §26.1).
  metrics               TEXT NOT NULL,
  result                TEXT NOT NULL
    CHECK (result IN ('create_work_item', 'rejected', 'support_changed', 'overridden')),
  -- Sticky-decision flag (design §11.3): set when the current aggregate no
  -- longer satisfies the rule, cleared when support returns. The original
  -- `metrics` snapshot is preserved either way.
  support_changed       INTEGER NOT NULL DEFAULT 0 CHECK (support_changed IN (0, 1)),
  override_reason       TEXT,
  work_item_id          TEXT,
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

-- Contract §4: THE idempotency constraint — concurrent threshold crossings
-- collapse to exactly one decision; losers treat the violation as
-- already-done, not error.
CREATE UNIQUE INDEX idx_decisions_idempotency
  ON decisions (source_annotation_id, action_type, rule_version);

CREATE INDEX idx_decisions_project ON decisions (project_id, id);

-- Contract §4 / design §13. `source_annotation_id` and `chapter_id` are not
-- foreign keys for the same rebuildability reason as decisions: work items
-- are restored from `.authorbot/work-items/<id>.md` artifacts.
CREATE TABLE work_items (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  type                  TEXT NOT NULL
    CHECK (type IN ('revise_range', 'revise_block', 'revise_chapter',
                    'write_chapter', 'resolve_conflict', 'planning')),
  -- Phase 3 stops at 'ready' (contract §1); the full Phase 0 §4 vocabulary
  -- is in-schema so Phase 4 needs no migration.
  status                TEXT NOT NULL DEFAULT 'ready'
    CHECK (status IN ('ready', 'leased', 'submitted', 'applying', 'completed',
                      'conflict', 'failed', 'cancelled')),
  source_annotation_id  TEXT NOT NULL,
  chapter_id            TEXT NOT NULL,
  base_revision         INTEGER NOT NULL CHECK (base_revision >= 1),
  -- JSON snapshot of the annotation target selector (incl. quote) at
  -- decision time; NULL for chapter-scope work.
  target                TEXT,
  priority              TEXT NOT NULL DEFAULT 'normal'
    CHECK (priority IN ('low', 'normal', 'high')),
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

CREATE INDEX idx_work_items_project_status ON work_items (project_id, status, id);

-- Contract §5 / design §15.5: the SSE event source. The monotonic
-- AUTOINCREMENT id is the stream cursor (`Last-Event-ID` / `?after=`);
-- AUTOINCREMENT (not plain rowid) guarantees ids are never reused, so a
-- resume cursor can never silently skip rows.
CREATE TABLE events (
  id                    INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  type                  TEXT NOT NULL,
  payload               TEXT NOT NULL,
  created_at            TEXT NOT NULL
);

CREATE INDEX idx_events_project ON events (project_id, id);
