-- Migration 0004: Phase 4 leases and submissions.
-- Phase 4 contract §2, §4, §6; design §12. Same single SQLite dialect for
-- Cloudflare D1 (production, `wrangler d1 migrations apply`) and
-- better-sqlite3 (tests/local dev, the Node runner in @authorbot/database).
--
-- Conventions follow 0001–0003: UUIDv7 TEXT primary keys generated by
-- callers; RFC 3339 UTC TEXT timestamps (fixed-width, so lexicographic
-- comparison equals chronological comparison); JSON payloads as TEXT.
--
-- Leases are OPERATIONAL-ONLY state (contract §6, design §13): they are
-- never mirrored to Git and intentionally do not survive a fresh-DB
-- projection rebuild (design §7.5).

-- Contract §2 / design §12.1–12.4.
--
-- DEFINITION OF "ACTIVE" (read carefully — two distinct notions):
--
--   * A lease is ACTIVE iff `released_at IS NULL AND revoked_at IS NULL`.
--     Active means "occupies the work item's single lease slot". This is
--     the predicate of the partial unique index below and the ONLY
--     condition the database enforces.
--
--   * A lease is LIVE (usable for renew/submit) iff it is active AND
--     `expires_at > now` — a lease is valid until, and not at, its
--     `expires_at` instant (same boundary as human_sessions:
--     expired ⇔ `expires_at <= now`). Expiry is deliberately NOT part of
--     the index predicate: it is a timestamp comparison made at query time
--     by every lease-relevant command (lazy enforcement, design §12.4), so
--     no submission is accepted merely because no sweep has run yet.
--
--   An expired-but-active lease therefore still holds the slot until it is
--   ENDED: either `released_at` set (voluntary release by the holder or a
--   maintainer, `POST .../lease/release`) or `revoked_at` set (involuntary
--   termination — lazy expiry inside a claim/renew/submit command, the
--   `sweepExpiredLeases` sweep, or an administrative revocation). Claiming
--   a work item whose lease has expired first ends that lease (sets
--   `revoked_at`) in the same batch as the new lease's INSERT
--   (design §12.2 step 1), which frees the unique-index slot atomically.
--
-- `token_hash` is the SHA-256 hex digest of the opaque 256-bit lease token.
-- The plaintext token is returned exactly once at claim time and is NEVER
-- stored or logged; verification is a constant-time compare of hashes in
-- the API layer.
CREATE TABLE leases (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  -- Not a foreign key: work_items rows are replaced wholesale by projection
  -- rebuilds (same rationale as decisions.source_annotation_id in 0002);
  -- leases must not block or be cascaded by that.
  work_item_id          TEXT NOT NULL,
  -- The holder (design §12: "holder actor").
  actor_id              TEXT NOT NULL REFERENCES actors (id),
  token_hash            TEXT NOT NULL,
  issued_at             TEXT NOT NULL,
  expires_at            TEXT NOT NULL,
  -- issued_at + maximum_total_duration (PT4H default): renewals may extend
  -- expires_at up to but never beyond this instant (design §12.3).
  max_expires_at        TEXT NOT NULL,
  renewal_count         INTEGER NOT NULL DEFAULT 0 CHECK (renewal_count >= 0),
  released_at           TEXT,
  revoked_at            TEXT
);

-- Contract §2: THE one-active-lease-per-work-item constraint. Enforced by
-- the index, not application hope: two simultaneous claims race on this
-- INSERT and exactly one wins; the loser maps the unique violation to a
-- typed LeaseHeld outcome (409 lease-held at the API).
CREATE UNIQUE INDEX idx_leases_active_work_item
  ON leases (work_item_id)
  WHERE released_at IS NULL AND revoked_at IS NULL;

-- Sweep support: active leases ordered by expiry, so
-- `sweepExpiredLeases(db, clock)` scans only the active slice.
CREATE INDEX idx_leases_active_expiry
  ON leases (expires_at)
  WHERE released_at IS NULL AND revoked_at IS NULL;

CREATE INDEX idx_leases_project ON leases (project_id, id);

-- Contract §2 (assignment) / contract §4, design §12.5. One row per accepted
-- `POST /work-items/{id}/submissions`; the row is created `received` after
-- the API-layer verification chain passes, then advances
-- received → applying → applied | conflicted, or → rejected. Content is
-- retained until completion/conflict resolution + 7 days (contract §6;
-- documented policy — no purge job in Phase 4).
CREATE TABLE submissions (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  -- Not foreign keys: work_items is rebuild-replaced (see leases above);
  -- lease_id references operational-only state that a fresh DB lacks.
  work_item_id          TEXT NOT NULL,
  lease_id              TEXT NOT NULL,
  actor_id              TEXT NOT NULL REFERENCES actors (id),
  type                  TEXT NOT NULL
    CHECK (type IN ('range_replacement', 'block_replacement', 'chapter_replacement')),
  base_revision         INTEGER NOT NULL CHECK (base_revision >= 1),
  -- "sha256:<hex>" of the chapter content at base_revision, echoed from the
  -- task bundle (contract §3) and verified against the lease's bundle.
  base_content_hash     TEXT NOT NULL,
  -- Replacement text (range/block) or full chapter Markdown (chapter);
  -- size-capped (≤ 512 KiB) and prose-safety-checked by the API before the
  -- row exists (contract §4).
  content               TEXT NOT NULL,
  summary               TEXT,
  notes                 TEXT,
  state                 TEXT NOT NULL DEFAULT 'received'
    CHECK (state IN ('received', 'applying', 'applied', 'conflicted', 'rejected')),
  -- The git_operations row tracking the apply commit (contract §4: 202
  -- returns { submissionId, operationId }). Set when the pipeline starts.
  git_operation_id      TEXT REFERENCES git_operations (id),
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

CREATE INDEX idx_submissions_work_item ON submissions (work_item_id, id);
CREATE INDEX idx_submissions_project_state ON submissions (project_id, state, id);
CREATE INDEX idx_submissions_lease ON submissions (lease_id);
