-- Migration 0005: Phase 5 reconciliation and publication tracking.
-- Phase 5 contract §6; design §14.5, §17.3, §20.3. Same single SQLite dialect
-- for Cloudflare D1 (production, `wrangler d1 migrations apply`) and
-- better-sqlite3 (tests/local dev, the Node runner in @authorbot/database).
--
-- Conventions follow 0001-0004: UUIDv7 TEXT primary keys generated by
-- callers; RFC 3339 UTC TEXT timestamps (fixed-width, so lexicographic
-- comparison equals chronological comparison); JSON payloads as TEXT.
--
-- ADDITIVE ONLY. The live deployment (Cloudflare Worker `causal-projector`,
-- D1 `authorbot`) is running the 0001-0004 schema; every column added here
-- carries a default that reproduces today's behaviour exactly, and no
-- existing column, index, or CHECK constraint is altered.

-- ---------------------------------------------------------------------------
-- Projection / divergence bookkeeping on `projects` (contract §6, design §14.5)
-- ---------------------------------------------------------------------------
--
-- `projection_stale` is set by the webhook the moment a verified `push` on the
-- default branch arrives, BEFORE any refresh is attempted, and cleared only by
-- a refresh that completed. That ordering is what makes a dropped or crashed
-- refresh recoverable: the flag survives, and the coordinator's periodic alarm
-- finds the work. A refresh-then-flag ordering would lose the push.
--
-- `projected_commit` is the repository commit the current projection was built
-- from (`BookRepoSnapshot.headCommit`). Design §20.3 reconciliation compares
-- it against the repository head and against the deployed commit; it is also
-- how "integrated" is defined for the publication gap.
--
-- Divergence (design §14.5) is recorded as `status = 'diverged'` plus the
-- machine-readable reason and the moment it was detected. `projects.status`
-- carries no CHECK constraint (0001), so this needs no constraint change, and
-- nothing in Phase 0-4 branches on `projects.status` - reads are unaffected by
-- construction. `divergence_reason` holds the JSON detection record (kind +
-- offending chapter/annotation ids) so the maintainer recovery endpoint can
-- explain what happened without re-reading the repository.
ALTER TABLE projects ADD COLUMN projection_stale INTEGER NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN projected_commit TEXT;
ALTER TABLE projects ADD COLUMN divergence_reason TEXT;
ALTER TABLE projects ADD COLUMN diverged_at TEXT;

-- ---------------------------------------------------------------------------
-- Publication state (design §17.3, contract §6)
-- ---------------------------------------------------------------------------
--
-- "Do not mark a revision published merely because its Git commit succeeded."
-- Nothing in the API ever writes this table from its own knowledge of a
-- commit: rows exist ONLY because CI called back and said so. The API's own
-- notion of progress is `projects.projected_commit` (integrated), and the gap
-- between that and `deployed_commit` is exactly what design §17.3 wants
-- visible.
--
-- One row per (project, integrated_commit): a single commit's publication
-- advances through several CI callbacks (`queued` → `building` → `succeeded`
-- → deployed, or → `failed`), each updating the same row. Deliveries are
-- deduped separately (see below), so a redelivered callback is a no-op rather
-- than a state change.
--
-- `build_status` vocabulary is closed by CHECK so an unknown CI value is a
-- rejected request rather than an unreadable row.
--
-- `deployed_commit` is nullable and deliberately NOT constrained to equal
-- `integrated_commit`: a publisher may deploy a merged/derived commit, and the
-- honest answer to "what is on the public page" is whatever CI reported, not
-- what we hoped. `deployed_at` and `public_url` are only meaningful alongside
-- it.
CREATE TABLE publications (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  -- Repository commit CI built from (design §17.3 "integrated commit SHA").
  integrated_commit     TEXT NOT NULL,
  build_status          TEXT NOT NULL
    CHECK (build_status IN ('queued', 'building', 'succeeded', 'failed')),
  -- Commit actually serving on the public site, per CI. NULL until deployed.
  deployed_commit       TEXT,
  public_url            TEXT,
  deployed_at           TEXT,
  publisher_version     TEXT,
  -- Delivery id of the callback that last advanced this row, for audit.
  last_delivery_id      TEXT,
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

-- One publication row per integrated commit per project (upsert target).
CREATE UNIQUE INDEX idx_publications_project_commit
  ON publications (project_id, integrated_commit);

-- "Latest publication" reads, ordered by `updated_at`: a long-running build for
-- an older commit can be touched after a newer row is created, so creation
-- order is the wrong answer to "what did CI last say?".
--
-- Note that `id` is only a tiebreak and NOT a total order: UUIDv7 sorts to
-- millisecond resolution with random low bits, so two callbacks inside the
-- same millisecond are genuinely unordered. This affects only which of two
-- near-simultaneous build statuses is reported as newest; the question that
-- must never be ambiguous - what is actually deployed - is answered by a
-- separate query filtered on `deployed_commit IS NOT NULL`.
CREATE INDEX idx_publications_project_recent
  ON publications (project_id, updated_at DESC, id DESC);

-- ---------------------------------------------------------------------------
-- Publication callback delivery dedupe (contract §6)
-- ---------------------------------------------------------------------------
--
-- Deliberately a separate table from `webhook_deliveries` rather than a
-- namespaced prefix in it: the two feeds have different senders, different
-- signature headers, and different replay semantics (a failed GitHub push
-- delivery is retryable on redelivery - app.ts webhook handler - whereas a
-- publication callback is a state report, so ANY repeat delivery id is a
-- no-op). Sharing one table would have forced one of those behaviours onto
-- the other.
--
-- `project_id` is part of the unique key so two projects' CI systems cannot
-- collide on a delivery id, and so the row is deletable with the project.
CREATE TABLE publication_deliveries (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  delivery_id           TEXT NOT NULL,
  -- Publication row this delivery advanced (NULL when it was rejected).
  publication_id        TEXT REFERENCES publications (id),
  status                TEXT NOT NULL DEFAULT 'received'
    CHECK (status IN ('received', 'processed', 'ignored', 'failed')),
  received_at           TEXT NOT NULL,
  processed_at          TEXT
);

CREATE UNIQUE INDEX idx_publication_deliveries_delivery
  ON publication_deliveries (project_id, delivery_id);
