-- Migration 0006: Phase 6 book settings and in-book governance.
-- Phase 6 contract §3.6; amends Phase 3 contract §3. Same single SQLite
-- dialect for Cloudflare D1 (production, `wrangler d1 migrations apply`) and
-- better-sqlite3 (tests/local dev, the Node runner in @authorbot/database).
--
-- Conventions follow 0001-0005: UUIDv7 TEXT primary keys generated by callers;
-- RFC 3339 UTC TEXT timestamps (fixed-width, so lexicographic comparison
-- equals chronological comparison); JSON payloads as TEXT.
--
-- ADDITIVE ONLY. The live deployment (Cloudflare Worker `causal-projector`,
-- D1 `authorbot`) runs the 0001-0005 schema; this migration adds one table and
-- alters nothing. A project with no row here behaves exactly as it does today:
-- settings reads report the book as unprojected, and governance falls back to
-- `RULES_JSON` and then to the built-in default rule.

-- ---------------------------------------------------------------------------
-- book_configs - the projection of the book's `book.yml` (contract §3.6)
-- ---------------------------------------------------------------------------
--
-- "Settings changes are commits: diffable, revertable, audited. There is no
-- second configuration store." This table is therefore a PROJECTION, not a
-- store of record: `book.yml` in Git is the truth, and every row here is
-- either a copy of a committed file or a copy of an accepted-but-not-yet-
-- committed one. It exists for the same reason the `annotations` table does -
-- a write must take effect on the next request without waiting for the outbox
-- to reach GitHub, and a read must not cost a round trip to the repository on
-- every vote.
--
-- One row per project (the project owns exactly one book), so `project_id` is
-- the primary key rather than a separate surrogate id.
CREATE TABLE book_configs (
  project_id            TEXT PRIMARY KEY REFERENCES projects (id),

  -- The full `authorbot.book/v1` document as JSON. Stored whole rather than
  -- shredded into columns: the API validates it against `bookConfigSchema` on
  -- the way in and on the way out, and PATCH is a read-modify-write of this
  -- document, so decomposing it would only create fields that must be kept in
  -- sync with a file this table does not own.
  config                TEXT NOT NULL,

  -- `pending_git` until the outbox commits the file, then `committed` -
  -- mirroring the annotation status vocabulary so the two mean the same thing.
  -- A settings read reports this so the UI can say "saving…" honestly instead
  -- of implying the commit already landed.
  status                TEXT NOT NULL DEFAULT 'committed'
    CHECK (status IN ('pending_git', 'committed')),

  -- The git operation that will commit (or committed) this revision; NULL for
  -- rows projected from the repository.
  git_operation_id      TEXT REFERENCES git_operations (id),

  -- Repository commit this config was read from, when it came from a
  -- projection pass. NULL for a pending write.
  source_commit         TEXT,

  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);
