-- Migration 0007: Phase 7 author-facing access control.
--
-- Phase 7 contract "Author-facing access control" (Restricting / Moderating /
-- Revoking) plus the Scope bullet on rate limits. Same single SQLite dialect
-- for Cloudflare D1 (production) and better-sqlite3 (tests/local dev).
--
-- Conventions follow 0001-0006: UUIDv7 TEXT primary keys generated by callers;
-- RFC 3339 UTC TEXT timestamps (fixed width, so lexicographic order equals
-- chronological order); JSON payloads as TEXT.
--
-- ADDITIVE ONLY. Three new tables, no ALTER of an existing one. A deployment
-- with no rows here behaves exactly as it did before this migration: the
-- annotation policy falls back to `collaborators-only` (the Phase 2 behaviour),
-- the book is not frozen, agents are not paused, and no request has yet been
-- counted against a rate-limit window.

-- ---------------------------------------------------------------------------
-- project_access_controls - the emergency stops (contract "Restricting")
-- ---------------------------------------------------------------------------
--
-- WHY THESE ARE NOT IN `book.yml`, unlike the annotation policy.
--
-- The annotation policy is an editorial decision about the book: who may
-- comment on it. It belongs in the repository, versioned and diffable beside
-- the prose it governs, and it is edited through the Phase 6 settings PATCH
-- like any other setting.
--
-- Freeze and pause-agents are neither editorial nor durable. They are the
-- author reaching for a switch because something is going wrong RIGHT NOW, and
-- three properties follow from that:
--
--   1. They must take effect on the next request, not on the next commit. A
--      settings PATCH is a 202: the config row lands immediately but the file
--      reaches Git asynchronously. That is right for a policy and wrong for a
--      stop button.
--   2. They must work when Git does not. The settings route refuses to write a
--      diverged project (`proseWriteBlocked`), and an unreachable GitHub App
--      leaves settings commits queued indefinitely. "I cannot stop the
--      runaway fleet because the repository is broken" is exactly the failure
--      an emergency control exists to prevent.
--   3. They are operational state, not book content. A restore drill that
--      rebuilds the projection from Git deliberately drops sessions, leases,
--      and agent tokens; a freeze belongs with those, not with the prose.
--
-- One row per project, so `project_id` is the primary key. NULL in a `*_at`
-- column means "not in effect" - the actor and reason columns beside it are
-- then meaningless and also NULL.
CREATE TABLE project_access_controls (
  project_id                TEXT PRIMARY KEY REFERENCES projects (id),

  -- Freeze: no writes at all, from anyone, INCLUDING maintainers, across
  -- annotations, votes, claims, and submissions. Reads are unaffected.
  frozen_at                 TEXT,
  frozen_by_actor_id        TEXT REFERENCES actors (id),
  freeze_reason             TEXT,

  -- Pause agents: every agent token is suspended at once while human
  -- collaborators keep working.
  agents_paused_at          TEXT,
  agents_paused_by_actor_id TEXT REFERENCES actors (id),
  agents_pause_reason       TEXT,

  created_at                TEXT NOT NULL,
  updated_at                TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- pending_annotations - the moderation queue (contract "Moderating")
-- ---------------------------------------------------------------------------
--
-- "Pending annotations are not mirrored to Git. They live in the operational
-- database until approved."
--
-- The load-bearing design choice is that this is a SEPARATE TABLE rather than
-- a new status on `annotations`. A pending row must accrue no votes, trigger no
-- governance rule, and reach no Git commit - three guarantees that a status
-- column can only deliver by every reader remembering to filter on it. Here
-- they are structural instead:
--
--   * `votes.annotation_id` is a foreign key into `annotations`, so a vote on a
--     pending row is not merely refused, it is unrepresentable.
--   * The rule engine evaluates tallies over `annotations`, which this row is
--     not in, so an unapproved suggestion cannot manufacture work.
--   * The Phase 2 mirror renders `annotations` rows from outbox entries. A
--     pending row has no git operation and no outbox entry, so there is no path
--     by which it could be committed.
--
-- Approval INSERTS into `annotations` - carrying this row's id forward, so the
-- author's link keeps working - and enqueues the ordinary `annotation.create`
-- outbox row. From that instant it is an annotation like any other. That is
-- what "approval is what makes a comment durable" means mechanically.
--
-- Rejection sets `status = 'rejected'` and keeps the row: "retains the record
-- in the database (never in Git) so a mistake is recoverable and a pattern of
-- abuse is visible."
CREATE TABLE pending_annotations (
  id                    TEXT PRIMARY KEY,
  project_id            TEXT NOT NULL REFERENCES projects (id),
  -- Not a foreign key, for the same reason `annotations.chapter_id` is not:
  -- projection rebuilds replace chapter rows, and a queued comment must
  -- survive one.
  chapter_id            TEXT NOT NULL,
  kind                  TEXT NOT NULL CHECK (kind IN ('comment', 'suggestion')),
  scope                 TEXT NOT NULL CHECK (scope IN ('range', 'block', 'chapter')),
  chapter_revision      INTEGER NOT NULL CHECK (chapter_revision >= 1),
  target                TEXT,
  author_actor_id       TEXT NOT NULL REFERENCES actors (id),
  body                  TEXT NOT NULL,

  status                TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),

  -- Who reviewed it and when. NULL while `pending`.
  reviewed_by_actor_id  TEXT REFERENCES actors (id),
  reviewed_at           TEXT,
  -- Optional, maintainer-authored, and never shown to the submitter (the
  -- contract: rejection "notifies nobody").
  rejection_reason      TEXT,
  -- The `annotations.id` an approval created. Equal to this row's `id` by
  -- construction; stored explicitly so the link is readable without knowing
  -- that invariant.
  approved_annotation_id TEXT,

  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

-- The queue view: one project's pending rows, oldest first.
CREATE INDEX idx_pending_annotations_queue
  ON pending_annotations (project_id, status, created_at);

-- The chapter view: a maintainer reading a chapter sees its queued comments,
-- and an author sees their own badged as awaiting review.
CREATE INDEX idx_pending_annotations_chapter
  ON pending_annotations (chapter_id, status);

-- An author's own queue, for the "author's history with this book" column the
-- moderation queue shows.
CREATE INDEX idx_pending_annotations_author
  ON pending_annotations (project_id, author_actor_id, status);

-- ---------------------------------------------------------------------------
-- rate_limit_counters - fixed-window mutation counters (contract Scope)
-- ---------------------------------------------------------------------------
--
-- "Rate limits per actor and per token on every mutation, with 429 +
-- Retry-After and documented ceilings."
--
-- A fixed window rather than a sliding log: the log would need a row per
-- request, and the point of the limit is to stop a fleet writing rows. One row
-- per (subject, class, window) costs a single upsert per mutation and is exact
-- enough for a control whose job is to blunt a runaway, not to meter billing.
--
-- `subject` is an actor id or a token id - both are opaque UUIDs from the same
-- generator, and a token's limit is checked in ADDITION to its owner's, so the
-- two never collide in meaning even when they share a table.
--
-- Rows are pruned opportunistically (`deleteExpired`) rather than by a job:
-- every window's rows are dead the moment the window closes, and the next
-- limiter call on the same subject is the cheapest place to notice.
CREATE TABLE rate_limit_counters (
  subject       TEXT NOT NULL,
  -- The limit class (`vote`, `claim`, `submission`, …) - see RATE_LIMITS in
  -- apps/api/src/rate-limit.ts, which is the documented ceiling table.
  class         TEXT NOT NULL,
  -- RFC 3339 UTC start of the window this row counts.
  window_start  TEXT NOT NULL,
  count         INTEGER NOT NULL DEFAULT 0,
  -- window_start + the class's window length: everything at or before `now`
  -- is prunable.
  expires_at    TEXT NOT NULL,
  PRIMARY KEY (subject, class, window_start)
);

CREATE INDEX idx_rate_limit_counters_expiry ON rate_limit_counters (expires_at);
