/**
 * Progressive revision comparison. The rendered comparison is the accessible
 * surface; a failed optional renderer reports an unavailable state instead of
 * dropping into a second, visually unrelated before-and-after reader.
 */
import { el } from "./dom.js";
import { loadLazyModule } from "./lazy-module.js";
import type {
  RevisionDiffLayout,
  renderRevisionDiffHtml,
} from "./revision-diff-core.js";
export type { RevisionDiffLayout } from "./revision-diff-core.js";

/** Below the two-reading-measure layout, history stays one column and diffs stay inline. */
export const REVISION_DIFF_COMPACT_QUERY = "(max-width: 1599px)";

export interface RevisionDiffInput {
  /** Bounded unified diff generated by the API; null means use snapshots only. */
  unifiedDiff: string | null;
  before: string;
  after: string;
  /** Accessible name for the complete comparison region. */
  label?: string;
}

interface RevisionDiffCore {
  renderRevisionDiffHtml: typeof renderRevisionDiffHtml;
}

export interface RevisionDiffRenderOptions {
  /** Injectable seams keep responsive and failed-chunk behavior deterministic in tests. */
  coreLoader?: () => Promise<RevisionDiffCore>;
  mediaQuery?: Pick<MediaQueryList, "matches" | "addEventListener" | "removeEventListener">;
  /** The owning panel keeps this choice stable across selected-diff rerenders. */
  preferredLayout?: RevisionDiffLayout | null;
  onPreferredLayoutChange?: (layout: RevisionDiffLayout) => void;
  /** Manuscript history uses independently flowing prose columns, not code rows. */
  proseFlow?: boolean;
}

export type RevisionDiffOutcome = "enhanced" | "unavailable";

export interface RevisionDiffHandle {
  /** Resolves after enhancement succeeds or settles safely on the fallback. */
  ready: Promise<RevisionDiffOutcome>;
  /** Stop responsive re-rendering when the owning review card is removed. */
  destroy(): void;
}

const ALLOWED_DIFF_ELEMENTS = new Set([
  "BR",
  "DEL",
  "DIV",
  "INS",
  "SPAN",
  "TABLE",
  "TBODY",
  "TD",
  "TR",
]);

/** Non-content Diff2Html chrome plus active/resource-loading HTML. */
const REMOVED_DIFF_ELEMENTS = new Set([
  "BUTTON",
  "EMBED",
  "FORM",
  "IFRAME",
  "IMG",
  "INPUT",
  "LABEL",
  "LINK",
  "META",
  "OBJECT",
  "PATH",
  "SCRIPT",
  "STYLE",
  "SVG",
]);

const loadCore = (): Promise<RevisionDiffCore> =>
  loadLazyModule(() => import("./revision-diff-core.js"));

/**
 * Mount a revision comparison. This function never rejects: a parser, chunk,
 * or malformed-diff failure is an expected progressive-enhancement outcome.
 */
export function renderRevisionDiff(
  host: HTMLElement,
  input: RevisionDiffInput,
  options: RevisionDiffRenderOptions = {},
): RevisionDiffHandle {
  host.classList.add("ab-revision-diff");
  host.setAttribute("role", "group");
  host.setAttribute("aria-label", input.label ?? "Revision comparison");
  host.textContent = "";

  if (options.proseFlow === true) {
    return renderProseFlowDiff(host, input, options);
  }

  const unifiedDiff = input.unifiedDiff;
  const hasUnifiedDiff = unifiedDiff !== null && unifiedDiff.trim() !== "";
  const status = el("p", "ab-revision-diff-status", "Loading visual comparison…");
  status.setAttribute("role", "status");
  host.append(status);

  let destroyed = false;
  let core: RevisionDiffCore | null = null;
  let visual: HTMLDivElement | null = null;
  let layoutControls: HTMLDivElement | null = null;
  let preferredLayout = options.preferredLayout ?? null;
  const media = hasUnifiedDiff ? (options.mediaQuery ?? matchCompact()) : null;
  const onLayoutChange = (): void => {
    if (!destroyed && core !== null && visual !== null && unifiedDiff !== null) {
      const layout = layoutFor(media, preferredLayout);
      drawVisual(visual, core, unifiedDiff, layout);
      updateLayoutControls(layoutControls, layout, media?.matches === true);
    }
  };
  media?.addEventListener("change", onLayoutChange);

  const ready: Promise<RevisionDiffOutcome> =
    !hasUnifiedDiff
      ? Promise.resolve(settleUnavailable(status))
      : (options.coreLoader ?? loadCore)()
          .then((loaded) => {
            if (destroyed) return "unavailable" as const;
            core = loaded;
            visual = el("div", "ab-revision-diff-visual");
            layoutControls = createLayoutControls((layout) => {
              if (layout === "side-by-side" && media?.matches === true) return;
              const preferenceChanged = preferredLayout !== layout;
              preferredLayout = layout;
              if (preferenceChanged) options.onPreferredLayoutChange?.(layout);
              const effective = layoutFor(media, preferredLayout);
              if (visual?.dataset.layout === effective) {
                updateLayoutControls(layoutControls, effective, media?.matches === true);
              } else {
                onLayoutChange();
              }
            });
            const layout = layoutFor(media, preferredLayout);
            drawVisual(visual, loaded, unifiedDiff, layout);
            updateLayoutControls(layoutControls, layout, media?.matches === true);
            host.append(layoutControls, visual);
            status.remove();
            return "enhanced" as const;
          })
          .catch(() =>
            destroyed ? ("unavailable" as const) : settleUnavailable(status),
          );

  return {
    ready,
    destroy(): void {
      destroyed = true;
      media?.removeEventListener("change", onLayoutChange);
    },
  };
}

type ManuscriptLineKind = "prose" | "code";

interface ManuscriptLine {
  value: string;
  kind: ManuscriptLineKind;
}

interface LinePair {
  before: ManuscriptLine | null;
  after: ManuscriptLine | null;
  changed: boolean;
}

interface TokenPart {
  value: string;
  changed: boolean;
  kind?: "removed" | "added";
}

function renderProseFlowDiff(
  host: HTMLElement,
  input: RevisionDiffInput,
  options: RevisionDiffRenderOptions,
): RevisionDiffHandle {
  const visual = el("div", "ab-prose-diff prose");
  let preferredLayout = options.preferredLayout ?? null;
  const media = options.mediaQuery ?? matchCompact();
  const controls = createLayoutControls((layout) => {
    if (layout === "side-by-side" && media?.matches === true) return;
    preferredLayout = layout;
    options.onPreferredLayoutChange?.(layout);
    draw();
  });
  const draw = (): void => {
    const layout = layoutFor(media, preferredLayout);
    visual.replaceChildren(proseDiffFragment(input.before, input.after, layout));
    visual.dataset.layout = layout;
    updateLayoutControls(controls, layout, media?.matches === true);
  };
  const onMediaChange = (): void => draw();
  media?.addEventListener("change", onMediaChange);
  draw();
  host.append(controls, visual);
  return {
    ready: Promise.resolve("enhanced"),
    destroy(): void {
      media?.removeEventListener("change", onMediaChange);
    },
  };
}

function proseDiffFragment(
  before: string,
  after: string,
  layout: RevisionDiffLayout,
): DocumentFragment {
  const fragment = document.createDocumentFragment();
  const pairs = alignLines(manuscriptLines(before), manuscriptLines(after));
  if (layout === "side-by-side") {
    const beforeColumn = el("section", "ab-prose-diff-column ab-prose-diff-before");
    const afterColumn = el("section", "ab-prose-diff-column ab-prose-diff-after");
    beforeColumn.append(el("h4", undefined, "Before"));
    afterColumn.append(el("h4", undefined, "After"));
    for (const pair of pairs) {
      if (!pair.changed) {
        if (pair.before !== null) {
          beforeColumn.append(proseLine(pair.before.value, "context", pair.before.kind));
          const afterLine = pair.after ?? pair.before;
          afterColumn.append(proseLine(afterLine.value, "context", afterLine.kind));
        }
        continue;
      }
      const parts = wordParts(pair.before?.value ?? "", pair.after?.value ?? "");
      if (pair.before !== null) {
        beforeColumn.append(proseLine(parts.before, "removed", pair.before.kind));
      }
      if (pair.after !== null) {
        afterColumn.append(proseLine(parts.after, "added", pair.after.kind));
      }
    }
    fragment.append(beforeColumn, afterColumn);
    return fragment;
  }
  const inline = el("section", "ab-prose-diff-column ab-prose-diff-inline");
  for (const pair of pairs) {
    if (!pair.changed) {
      if (pair.before !== null) {
        inline.append(proseLine(pair.before.value, "context", pair.before.kind));
      }
      continue;
    }
    inline.append(
      proseLine(
        inlineWordParts(pair.before?.value ?? "", pair.after?.value ?? ""),
        "context",
        pair.after?.kind ?? pair.before?.kind ?? "prose",
      ),
    );
  }
  fragment.append(inline);
  return fragment;
}

function proseLine(
  content: string | readonly TokenPart[],
  kind: "context" | "removed" | "added",
  manuscriptKind: ManuscriptLineKind,
): HTMLElement {
  const line = el(
    "p",
    `ab-prose-diff-line ab-prose-diff-${kind} ab-prose-diff-${manuscriptKind}-line`,
  );
  if (typeof content === "string") {
    line.textContent = content === "" ? " " : content;
    return line;
  }
  for (const part of content) {
    if (!part.changed || /^\s+$/u.test(part.value)) {
      line.append(document.createTextNode(part.value));
      continue;
    }
    const partKind = part.kind ?? kind;
    const mark = el(partKind === "removed" ? "del" : "ins", undefined, part.value);
    line.append(mark);
  }
  if (line.textContent === "") line.textContent = " ";
  return line;
}

function manuscriptLines(source: string): ManuscriptLine[] {
  const lines = source.replace(/\r\n?/gu, "\n").split("\n");
  let index = 0;
  if (lines[0]?.trim() === "---") {
    index = 1;
    while (index < lines.length && lines[index]?.trim() !== "---") index += 1;
    if (index < lines.length) index += 1;
  }
  const result: ManuscriptLine[] = [];
  let fence: { marker: "`" | "~"; length: number } | null = null;
  for (const rawLine of lines.slice(index)) {
    const fenceMatch = /^\s*(`{3,}|~{3,})(.*)$/u.exec(rawLine);
    if (fenceMatch !== null) {
      const token = fenceMatch[1] ?? "";
      const marker = token[0] as "`" | "~";
      const suffix = fenceMatch[2] ?? "";
      if (fence === null) {
        fence = { marker, length: token.length };
        continue;
      }
      if (marker === fence.marker && token.length >= fence.length && suffix.trim() === "") {
        fence = null;
        continue;
      }
    }
    if (fence !== null) {
      result.push({ value: rawLine, kind: "code" });
      continue;
    }
    if (/^\s*<!--\s*authorbot:block\b.*-->\s*$/u.test(rawLine)) continue;
    const value = rawLine
      .replace(/^\s{0,3}#{1,6}\s+/u, "")
      .replace(/^\s*>\s?/u, "")
      .replace(/^\s*(?:[-+*]|\d+[.)])\s+/u, "")
      .replace(/!\[([^\]]*)\]\([^)]*\)/gu, "$1")
      .replace(/\[([^\]]+)\]\([^)]*\)/gu, "$1")
      .replace(/(\*\*|__|\*|_|~~|`)(.*?)\1/gu, "$2")
      .trim();
    if (value !== "") result.push({ value, kind: "prose" });
  }
  return result;
}

function sameLine(
  before: ManuscriptLine | undefined,
  after: ManuscriptLine | undefined,
): boolean {
  return (
    before !== undefined &&
    after !== undefined &&
    before.value === after.value &&
    before.kind === after.kind
  );
}

function alignLines(
  before: readonly ManuscriptLine[],
  after: readonly ManuscriptLine[],
): LinePair[] {
  const width = after.length + 1;
  if (before.length * after.length > 250_000) {
    return Array.from({ length: Math.max(before.length, after.length) }, (_, index) => ({
      before: before[index] ?? null,
      after: after[index] ?? null,
      changed: !sameLine(before[index], after[index]),
    }));
  }
  const table = new Uint32Array((before.length + 1) * width);
  const score = (row: number, column: number): number =>
    table[row * width + column] ?? 0;
  for (let left = before.length - 1; left >= 0; left -= 1) {
    for (let right = after.length - 1; right >= 0; right -= 1) {
      table[left * width + right] =
        sameLine(before[left], after[right])
          ? score(left + 1, right + 1) + 1
          : Math.max(score(left + 1, right), score(left, right + 1));
    }
  }
  const pairs: LinePair[] = [];
  let left = 0;
  let right = 0;
  let removed: ManuscriptLine[] = [];
  let added: ManuscriptLine[] = [];
  const flush = (): void => {
    const count = Math.max(removed.length, added.length);
    for (let index = 0; index < count; index += 1) {
      pairs.push({
        before: removed[index] ?? null,
        after: added[index] ?? null,
        changed: true,
      });
    }
    removed = [];
    added = [];
  };
  while (left < before.length && right < after.length) {
    if (sameLine(before[left], after[right])) {
      flush();
      pairs.push({
        before: before[left] ?? null,
        after: after[right] ?? null,
        changed: false,
      });
      left += 1;
      right += 1;
    } else if (
      score(left + 1, right) >= score(left, right + 1)
    ) {
      const line = before[left];
      if (line !== undefined) removed.push(line);
      left += 1;
    } else {
      const line = after[right];
      if (line !== undefined) added.push(line);
      right += 1;
    }
  }
  removed.push(...before.slice(left));
  added.push(...after.slice(right));
  flush();
  return pairs;
}

function wordParts(
  before: string,
  after: string,
): { before: TokenPart[]; after: TokenPart[] } {
  const beforeParts: TokenPart[] = [];
  const afterParts: TokenPart[] = [];
  for (const pair of alignSentences(sentenceParts(before), sentenceParts(after))) {
    if (!pair.changed) {
      if (pair.before !== null) {
        beforeParts.push({ value: pair.before.value, changed: false });
      }
      if (pair.after !== null) {
        afterParts.push({ value: pair.after.value, changed: false });
      }
      continue;
    }
    if (
      pair.before !== null &&
      pair.after !== null &&
      sentenceSimilarity(pair.before.value, pair.after.value) >= 0.56
    ) {
      const localized = basicWordParts(pair.before.value, pair.after.value);
      beforeParts.push(...localized.before);
      afterParts.push(...localized.after);
      continue;
    }
    if (pair.before !== null) {
      beforeParts.push({ value: pair.before.value, changed: true });
    }
    if (pair.after !== null) {
      afterParts.push({ value: pair.after.value, changed: true });
    }
  }
  return { before: beforeParts, after: afterParts };
}

interface SentencePart {
  value: string;
  key: string;
}

interface SentencePair {
  before: SentencePart | null;
  after: SentencePart | null;
  changed: boolean;
}

function sentenceParts(value: string): SentencePart[] {
  if (value === "") return [];
  const fallback = (): string[] =>
    value.match(/[^.!?]+(?:[.!?]+(?:["'”’)\]]*)|$)/gu) ?? [value];
  let segments: string[];
  try {
    const segmenter = new Intl.Segmenter(undefined, { granularity: "sentence" });
    segments = Array.from(segmenter.segment(value), (part) => part.segment);
  } catch {
    segments = fallback();
  }
  return segments
    .filter((segment) => segment !== "")
    .map((segment) => ({
      value: segment,
      key: segment.trim(),
    }));
}

function alignSentences(
  before: readonly SentencePart[],
  after: readonly SentencePart[],
): SentencePair[] {
  const width = after.length + 1;
  const table = new Uint32Array((before.length + 1) * width);
  const score = (row: number, column: number): number =>
    table[row * width + column] ?? 0;
  for (let left = before.length - 1; left >= 0; left -= 1) {
    for (let right = after.length - 1; right >= 0; right -= 1) {
      table[left * width + right] =
        before[left]?.key === after[right]?.key
          ? score(left + 1, right + 1) + 1
          : Math.max(score(left + 1, right), score(left, right + 1));
    }
  }
  const pairs: SentencePair[] = [];
  let left = 0;
  let right = 0;
  let removed: SentencePart[] = [];
  let added: SentencePart[] = [];
  const flush = (): void => {
    const count = Math.max(removed.length, added.length);
    for (let index = 0; index < count; index += 1) {
      pairs.push({
        before: removed[index] ?? null,
        after: added[index] ?? null,
        changed: true,
      });
    }
    removed = [];
    added = [];
  };
  while (left < before.length && right < after.length) {
    if (before[left]?.key === after[right]?.key) {
      flush();
      pairs.push({
        before: before[left] ?? null,
        after: after[right] ?? null,
        changed: false,
      });
      left += 1;
      right += 1;
    } else if (score(left + 1, right) >= score(left, right + 1)) {
      const part = before[left];
      if (part !== undefined) removed.push(part);
      left += 1;
    } else {
      const part = after[right];
      if (part !== undefined) added.push(part);
      right += 1;
    }
  }
  removed.push(...before.slice(left));
  added.push(...after.slice(right));
  flush();
  return pairs;
}

function sentenceSimilarity(before: string, after: string): number {
  const left = before.toLocaleLowerCase().match(/[\p{L}\p{N}_]+/gu) ?? [];
  const right = after.toLocaleLowerCase().match(/[\p{L}\p{N}_]+/gu) ?? [];
  if (left.length === 0 || right.length === 0) return 0;
  const width = right.length + 1;
  const table = new Uint16Array((left.length + 1) * width);
  const score = (row: number, column: number): number =>
    table[row * width + column] ?? 0;
  for (let i = left.length - 1; i >= 0; i -= 1) {
    for (let j = right.length - 1; j >= 0; j -= 1) {
      table[i * width + j] =
        left[i] === right[j]
          ? score(i + 1, j + 1) + 1
          : Math.max(score(i + 1, j), score(i, j + 1));
    }
  }
  return (2 * score(0, 0)) / (left.length + right.length);
}

function basicWordParts(
  before: string,
  after: string,
): { before: TokenPart[]; after: TokenPart[] } {
  const tokenize = (value: string): string[] =>
    value.match(/\s+|[\p{L}\p{N}_]+|[^\s\p{L}\p{N}_]+/gu) ?? [];
  const left = tokenize(before);
  const right = tokenize(after);
  if (left.length * right.length > 250_000) {
    return {
      before: [{ value: before, changed: true }],
      after: [{ value: after, changed: true }],
    };
  }
  const width = right.length + 1;
  const table = new Uint32Array((left.length + 1) * width);
  const score = (row: number, column: number): number =>
    table[row * width + column] ?? 0;
  for (let i = left.length - 1; i >= 0; i -= 1) {
    for (let j = right.length - 1; j >= 0; j -= 1) {
      table[i * width + j] =
        left[i] === right[j]
          ? score(i + 1, j + 1) + 1
          : Math.max(score(i + 1, j), score(i, j + 1));
    }
  }
  const leftParts: TokenPart[] = [];
  const rightParts: TokenPart[] = [];
  let i = 0;
  let j = 0;
  while (i < left.length && j < right.length) {
    if (left[i] === right[j]) {
      leftParts.push({ value: left[i] ?? "", changed: false });
      rightParts.push({ value: right[j] ?? "", changed: false });
      i += 1;
      j += 1;
    } else if (score(i + 1, j) >= score(i, j + 1)) {
      leftParts.push({ value: left[i] ?? "", changed: true });
      i += 1;
    } else {
      rightParts.push({ value: right[j] ?? "", changed: true });
      j += 1;
    }
  }
  for (; i < left.length; i += 1) {
    leftParts.push({ value: left[i] ?? "", changed: true });
  }
  for (; j < right.length; j += 1) {
    rightParts.push({ value: right[j] ?? "", changed: true });
  }
  return { before: leftParts, after: rightParts };
}

function inlineWordParts(before: string, after: string): TokenPart[] {
  const parts: TokenPart[] = [];
  for (const pair of alignSentences(sentenceParts(before), sentenceParts(after))) {
    if (!pair.changed) {
      if (pair.after !== null) {
        parts.push({ value: pair.after.value, changed: false });
      } else if (pair.before !== null) {
        parts.push({ value: pair.before.value, changed: false });
      }
      continue;
    }
    if (
      pair.before !== null &&
      pair.after !== null &&
      sentenceSimilarity(pair.before.value, pair.after.value) >= 0.56
    ) {
      parts.push(...basicInlineWordParts(pair.before.value, pair.after.value));
      continue;
    }
    if (pair.before !== null) {
      parts.push({ value: pair.before.value, changed: true, kind: "removed" });
    }
    if (pair.after !== null) {
      parts.push({ value: pair.after.value, changed: true, kind: "added" });
    }
  }
  return parts;
}

function basicInlineWordParts(before: string, after: string): TokenPart[] {
  const tokenize = (value: string): string[] =>
    value.match(/\s+|[\p{L}\p{N}_]+|[^\s\p{L}\p{N}_]+/gu) ?? [];
  const left = tokenize(before);
  const right = tokenize(after);
  if (left.length * right.length > 250_000) {
    return [
      ...(before === "" ? [] : [{ value: before, changed: true, kind: "removed" as const }]),
      ...(after === "" ? [] : [{ value: after, changed: true, kind: "added" as const }]),
    ];
  }
  const width = right.length + 1;
  const table = new Uint32Array((left.length + 1) * width);
  const score = (row: number, column: number): number =>
    table[row * width + column] ?? 0;
  for (let i = left.length - 1; i >= 0; i -= 1) {
    for (let j = right.length - 1; j >= 0; j -= 1) {
      table[i * width + j] =
        left[i] === right[j]
          ? score(i + 1, j + 1) + 1
          : Math.max(score(i + 1, j), score(i, j + 1));
    }
  }
  const parts: TokenPart[] = [];
  let i = 0;
  let j = 0;
  while (i < left.length && j < right.length) {
    if (left[i] === right[j]) {
      parts.push({ value: left[i] ?? "", changed: false });
      i += 1;
      j += 1;
    } else if (score(i + 1, j) >= score(i, j + 1)) {
      parts.push({ value: left[i] ?? "", changed: true, kind: "removed" });
      i += 1;
    } else {
      parts.push({ value: right[j] ?? "", changed: true, kind: "added" });
      j += 1;
    }
  }
  for (; i < left.length; i += 1) {
    parts.push({ value: left[i] ?? "", changed: true, kind: "removed" });
  }
  for (; j < right.length; j += 1) {
    parts.push({ value: right[j] ?? "", changed: true, kind: "added" });
  }
  return parts;
}

function matchCompact(): Pick<
  MediaQueryList,
  "matches" | "addEventListener" | "removeEventListener"
> | null {
  return typeof window.matchMedia === "function"
    ? window.matchMedia(REVISION_DIFF_COMPACT_QUERY)
    : null;
}

function layoutFor(
  media: Pick<MediaQueryList, "matches"> | null,
  preferred: RevisionDiffLayout | null,
): RevisionDiffLayout {
  if (media?.matches === true) return "line-by-line";
  return preferred ?? "side-by-side";
}

function createLayoutControls(
  select: (layout: RevisionDiffLayout) => void,
): HTMLDivElement {
  const controls = el("div", "ab-revision-diff-layout");
  controls.setAttribute("role", "group");
  controls.setAttribute("aria-label", "Diff layout");
  for (const [layout, label] of [
    ["line-by-line", "Inline"],
    ["side-by-side", "Side by side"],
  ] as const) {
    const button = el("button", "ab-revision-diff-layout-button", label);
    button.type = "button";
    button.dataset.layout = layout;
    button.addEventListener("click", () => select(layout));
    controls.append(button);
  }
  return controls;
}

function updateLayoutControls(
  controls: HTMLDivElement | null,
  layout: RevisionDiffLayout,
  compact: boolean,
): void {
  if (controls === null) return;
  controls.hidden = compact;
  for (const button of controls.querySelectorAll<HTMLButtonElement>("button[data-layout]")) {
    button.setAttribute("aria-pressed", String(button.dataset.layout === layout));
    button.disabled = compact && button.dataset.layout === "side-by-side";
  }
}

function settleUnavailable(status: HTMLParagraphElement): RevisionDiffOutcome {
  status.textContent = "Visual comparison unavailable.";
  return "unavailable";
}

function drawVisual(
  visual: HTMLDivElement,
  core: RevisionDiffCore,
  unifiedDiff: string,
  layout: RevisionDiffLayout,
): void {
  const rendered = core.renderRevisionDiffHtml(unifiedDiff, layout);
  visual.replaceChildren(safeDiffFragment(rendered));
  visual.dataset.layout = layout;
}

/**
 * Diff2Html escapes line text itself. This second, deliberately narrow DOM
 * allowlist is defense in depth against a future renderer/template regression:
 * only its inert table/text structure and class names reach the live document.
 */
function safeDiffFragment(rendered: string): DocumentFragment {
  const parsed = new DOMParser().parseFromString(rendered, "text/html");
  for (const row of parsed.body.querySelectorAll("tr")) {
    if (
      row.querySelector(".d2h-info") !== null &&
      /^@@(?:\s|$)/u.test(row.textContent?.trim() ?? "")
    ) {
      row.remove();
    }
  }
  for (const gutter of parsed.body.querySelectorAll(
    ".d2h-code-linenumber, .d2h-code-side-linenumber",
  )) {
    gutter.remove();
  }
  const elements = Array.from(parsed.body.querySelectorAll("*"));
  for (const element of elements) {
    if (REMOVED_DIFF_ELEMENTS.has(element.tagName)) {
      element.remove();
      continue;
    }
    if (!ALLOWED_DIFF_ELEMENTS.has(element.tagName)) {
      unwrap(element);
      continue;
    }
    for (const attribute of Array.from(element.attributes)) {
      if (attribute.name !== "class") element.removeAttribute(attribute.name);
    }
  }

  const fragment = document.createDocumentFragment();
  for (const child of Array.from(parsed.body.childNodes)) {
    fragment.append(document.importNode(child, true));
  }
  return fragment;
}

/** Remove an unknown element while retaining any plain text nested inside it. */
function unwrap(element: Element): void {
  const parent = element.parentNode;
  if (parent === null) return;
  while (element.firstChild !== null) {
    parent.insertBefore(element.firstChild, element);
  }
  element.remove();
}
