/**
 * Progressive revision comparison.
 *
 * Before the optional renderer chunk arrives, and whenever it cannot arrive,
 * the complete before/after snapshots remain available as escaped plain text.
 * The visual Diff2Html table is supplemental (`aria-hidden`): assistive
 * technology gets the simpler labelled snapshots instead of a repeated maze
 * of presentational line-number cells.
 */
import { el } from "./dom.js";
import { loadLazyModule } from "./lazy-module.js";
import type {
  RevisionDiffLayout,
  renderRevisionDiffHtml,
} from "./revision-diff-core.js";

export const REVISION_DIFF_MOBILE_QUERY = "(max-width: 719px)";

export interface RevisionDiffInput {
  /** Bounded unified diff generated by the API; null means use snapshots only. */
  unifiedDiff: string | null;
  before: string;
  after: string;
  /** Accessible name for the complete comparison region. */
  label?: string;
}

interface RevisionDiffCore {
  renderRevisionDiffHtml: typeof renderRevisionDiffHtml;
}

export interface RevisionDiffRenderOptions {
  /** Injectable seams keep responsive and failed-chunk behavior deterministic in tests. */
  coreLoader?: () => Promise<RevisionDiffCore>;
  mediaQuery?: Pick<MediaQueryList, "matches" | "addEventListener" | "removeEventListener">;
}

export type RevisionDiffOutcome = "enhanced" | "fallback";

export interface RevisionDiffHandle {
  /** Resolves after enhancement succeeds or settles safely on the fallback. */
  ready: Promise<RevisionDiffOutcome>;
  /** Stop responsive re-rendering when the owning review card is removed. */
  destroy(): void;
}

const ALLOWED_DIFF_ELEMENTS = new Set([
  "BR",
  "DEL",
  "DIV",
  "INS",
  "SPAN",
  "TABLE",
  "TBODY",
  "TD",
  "TR",
]);

/** Non-content Diff2Html chrome plus active/resource-loading HTML. */
const REMOVED_DIFF_ELEMENTS = new Set([
  "BUTTON",
  "EMBED",
  "FORM",
  "IFRAME",
  "IMG",
  "INPUT",
  "LABEL",
  "LINK",
  "META",
  "OBJECT",
  "PATH",
  "SCRIPT",
  "STYLE",
  "SVG",
]);

const loadCore = (): Promise<RevisionDiffCore> =>
  loadLazyModule(() => import("./revision-diff-core.js"));

/**
 * Mount a revision comparison. This function never rejects: a parser, chunk,
 * or malformed-diff failure is an expected progressive-enhancement outcome.
 */
export function renderRevisionDiff(
  host: HTMLElement,
  input: RevisionDiffInput,
  options: RevisionDiffRenderOptions = {},
): RevisionDiffHandle {
  host.classList.add("ab-revision-diff");
  host.setAttribute("role", "group");
  host.setAttribute("aria-label", input.label ?? "Revision comparison");
  host.textContent = "";

  const fallback = createPlainComparison(input.before, input.after);
  const status = el("p", "ab-revision-diff-status", "Loading visual comparison…");
  status.setAttribute("role", "status");
  host.append(status, fallback);

  let destroyed = false;
  let core: RevisionDiffCore | null = null;
  let visual: HTMLDivElement | null = null;
  const unifiedDiff = input.unifiedDiff;
  const hasUnifiedDiff = unifiedDiff !== null && unifiedDiff.trim() !== "";
  const media = hasUnifiedDiff ? (options.mediaQuery ?? matchMobile()) : null;
  const onLayoutChange = (): void => {
    if (!destroyed && core !== null && visual !== null && unifiedDiff !== null) {
      drawVisual(visual, core, unifiedDiff, layoutFor(media));
    }
  };
  media?.addEventListener("change", onLayoutChange);

  const ready: Promise<RevisionDiffOutcome> =
    !hasUnifiedDiff
      ? Promise.resolve(settleOnFallback(status, fallback))
      : (options.coreLoader ?? loadCore)()
          .then((loaded) => {
            if (destroyed) return "fallback" as const;
            core = loaded;
            visual = el("div", "ab-revision-diff-visual");
            visual.setAttribute("aria-hidden", "true");
            drawVisual(visual, loaded, unifiedDiff, layoutFor(media));
            host.insertBefore(visual, fallback);
            fallback.open = false;
            status.remove();
            return "enhanced" as const;
          })
          .catch(() =>
            destroyed ? ("fallback" as const) : settleOnFallback(status, fallback),
          );

  return {
    ready,
    destroy(): void {
      destroyed = true;
      media?.removeEventListener("change", onLayoutChange);
    },
  };
}

function matchMobile(): Pick<
  MediaQueryList,
  "matches" | "addEventListener" | "removeEventListener"
> | null {
  return typeof window.matchMedia === "function"
    ? window.matchMedia(REVISION_DIFF_MOBILE_QUERY)
    : null;
}

function layoutFor(
  media: Pick<MediaQueryList, "matches"> | null,
): RevisionDiffLayout {
  return media?.matches === true ? "line-by-line" : "side-by-side";
}

function createPlainComparison(before: string, after: string): HTMLDetailsElement {
  const details = el("details", "ab-revision-diff-fallback");
  details.open = true;
  details.append(el("summary", undefined, "Plain-text before and after"));
  details.append(snapshot("Before", before), snapshot("After", after));
  return details;
}

function snapshot(label: string, content: string): HTMLElement {
  const section = el("section", "ab-revision-diff-snapshot");
  section.setAttribute("aria-label", label);
  const pre = el("pre");
  const code = el("code", undefined, content);
  pre.append(code);
  section.append(el("h3", undefined, label), pre);
  return section;
}

function settleOnFallback(
  status: HTMLParagraphElement,
  fallback: HTMLDetailsElement,
): RevisionDiffOutcome {
  fallback.open = true;
  status.textContent =
    "Visual comparison unavailable. The complete plain-text comparison remains available.";
  return "fallback";
}

function drawVisual(
  visual: HTMLDivElement,
  core: RevisionDiffCore,
  unifiedDiff: string,
  layout: RevisionDiffLayout,
): void {
  const rendered = core.renderRevisionDiffHtml(unifiedDiff, layout);
  visual.replaceChildren(safeDiffFragment(rendered));
  visual.dataset.layout = layout;
}

/**
 * Diff2Html escapes line text itself. This second, deliberately narrow DOM
 * allowlist is defense in depth against a future renderer/template regression:
 * only its inert table/text structure and class names reach the live document.
 */
function safeDiffFragment(rendered: string): DocumentFragment {
  const parsed = new DOMParser().parseFromString(rendered, "text/html");
  const elements = Array.from(parsed.body.querySelectorAll("*"));
  for (const element of elements) {
    if (REMOVED_DIFF_ELEMENTS.has(element.tagName)) {
      element.remove();
      continue;
    }
    if (!ALLOWED_DIFF_ELEMENTS.has(element.tagName)) {
      unwrap(element);
      continue;
    }
    for (const attribute of Array.from(element.attributes)) {
      if (attribute.name !== "class") element.removeAttribute(attribute.name);
    }
  }

  const fragment = document.createDocumentFragment();
  for (const child of Array.from(parsed.body.childNodes)) {
    fragment.append(document.importNode(child, true));
  }
  return fragment;
}

/** Remove an unknown element while retaining any plain text nested inside it. */
function unwrap(element: Element): void {
  const parent = element.parentNode;
  if (parent === null) return;
  while (element.firstChild !== null) {
    parent.insertBefore(element.firstChild, element);
  }
  element.remove();
}
