/**
 * Typed records for the Phase 2 operational tables (contract §2, design
 * §9.1/§9.2). Field names are camelCase; columns are snake_case. IDs are
 * UUIDv7 strings generated by callers; timestamps are RFC 3339 UTC strings.
 * JSON-valued columns (`scopes`, `target`, `payload`, `metadata`) are
 * (de)serialized by the repositories.
 */

export type ActorType = "human" | "agent" | "system";

export type MembershipRole = "reader" | "contributor" | "editor" | "maintainer";

export type ChapterStatus = "draft" | "proposed" | "published" | "archived";

export type AnnotationKind = "comment" | "suggestion";

export type AnnotationScope = "range" | "block" | "chapter";

/**
 * Annotation record status: the Phase 0 domain statuses plus `pending_git`,
 * the initial state of a record whose Git mirror commit is still queued
 * (Phase 2 contract §5: records leave `pending_git` only after commit).
 */
export type AnnotationRecordStatus =
  | "pending_git"
  | "open"
  | "work_item_created"
  | "accepted"
  | "resolved"
  | "rejected"
  | "withdrawn"
  | "superseded"
  | "orphaned"
  | "needs_reanchor";

export type ReplyRecordStatus = "pending_git" | "open" | "withdrawn";

/** design §20.2 */
export type GitOperationState =
  | "queued"
  | "preparing"
  | "committing"
  | "committed"
  | "verified"
  | "conflict"
  | "failed";

export type OutboxStatus = "pending" | "processing" | "done" | "failed";

export type WebhookDeliveryStatus = "received" | "processed" | "ignored" | "failed";

export interface ProjectRecord {
  id: string;
  slug: string;
  repoProvider: string;
  /** Repository coordinates, e.g. `JoeMattie/causal-projector`. */
  repo: string;
  defaultBranch: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface ActorRecord {
  id: string;
  type: ActorType;
  displayName: string;
  /** `<namespace>:<identifier>` per Phase 0 contract §2, e.g. `github:octocat`. */
  externalIdentity: string | null;
  ownerActorId: string | null;
  status: string;
  createdAt: string;
}

export interface ProjectMembershipRecord {
  id: string;
  projectId: string;
  actorId: string;
  role: MembershipRole;
  scopes: string[];
  createdAt: string;
  revokedAt: string | null;
}

export interface HumanSessionRecord {
  id: string;
  /** SHA-256 hash of the opaque session id. Plaintext is never stored. */
  sessionHash: string;
  actorId: string;
  createdAt: string;
  expiresAt: string;
  revokedAt: string | null;
}

export interface AgentTokenRecord {
  id: string;
  projectId: string;
  actorId: string;
  name: string;
  /** SHA-256 hash of the token. Plaintext is never stored. */
  tokenHash: string;
  scopes: string[];
  createdBy: string;
  createdAt: string;
  expiresAt: string;
  revokedAt: string | null;
  lastUsedAt: string | null;
}

export interface ChapterProjectionRecord {
  id: string;
  projectId: string;
  path: string;
  slug: string;
  title: string;
  status: ChapterStatus;
  revision: number;
  contentHash: string;
  headCommit: string | null;
  lastPublishedCommit: string | null;
  /**
   * Valid block-marker ids of this projected revision. Persisted (contract
   * §4) so blockId-existence validation works from the database alone.
   */
  blockIds: string[];
  updatedAt: string;
}

export interface AnnotationRecord {
  id: string;
  projectId: string;
  chapterId: string;
  kind: AnnotationKind;
  scope: AnnotationScope;
  chapterRevision: number;
  /** Target selector payload (design §10.1); null for chapter scope. */
  target: unknown;
  authorActorId: string;
  body: string;
  status: AnnotationRecordStatus;
  gitOperationId: string | null;
  supersededBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ReplyRecord {
  id: string;
  projectId: string;
  annotationId: string;
  parentReplyId: string | null;
  authorActorId: string;
  body: string;
  status: ReplyRecordStatus;
  gitOperationId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface GitOperationRecord {
  id: string;
  projectId: string;
  correlationId: string;
  expectedHead: string | null;
  state: GitOperationState;
  attempts: number;
  commitSha: string | null;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface OutboxRecord {
  id: string;
  projectId: string;
  gitOperationId: string | null;
  kind: string;
  payload: unknown;
  status: OutboxStatus;
  attempts: number;
  createdAt: string;
  processedAt: string | null;
}

export interface IdempotencyKeyRecord {
  id: string;
  projectId: string;
  actorId: string;
  key: string;
  requestHash: string;
  responseStatus: number | null;
  responseBody: string | null;
  createdAt: string;
}

export interface WebhookDeliveryRecord {
  id: string;
  deliveryId: string;
  event: string;
  status: WebhookDeliveryStatus;
  receivedAt: string;
  processedAt: string | null;
}

export interface AuditEventRecord {
  id: string;
  projectId: string;
  actorId: string | null;
  action: string;
  targetType: string;
  targetId: string | null;
  correlationId: string;
  /** Safe metadata only — never token/session material (design §20.6). */
  metadata: unknown;
  createdAt: string;
}
