/**
 * Typed records for the Phase 2 operational tables (contract §2, design
 * §9.1/§9.2). Field names are camelCase; columns are snake_case. IDs are
 * UUIDv7 strings generated by callers; timestamps are RFC 3339 UTC strings.
 * JSON-valued columns (`scopes`, `target`, `payload`, `metadata`) are
 * (de)serialized by the repositories.
 */

export type ActorType = "human" | "agent" | "system";

export type MembershipRole = "reader" | "contributor" | "editor" | "maintainer";

export type ChapterStatus = "draft" | "proposed" | "published" | "archived";

export type AnnotationKind = "comment" | "suggestion";

export type AnnotationScope = "range" | "block" | "chapter";

/**
 * Annotation record status: the Phase 0 domain statuses plus `pending_git`,
 * the initial state of a record whose Git mirror commit is still queued
 * (Phase 2 contract §5: records leave `pending_git` only after commit).
 */
export type AnnotationRecordStatus =
  | "pending_git"
  | "open"
  | "work_item_created"
  | "accepted"
  | "resolved"
  | "rejected"
  | "withdrawn"
  | "superseded"
  | "orphaned"
  | "needs_reanchor";

export type ReplyRecordStatus = "pending_git" | "open" | "withdrawn";

/** design §20.2 */
export type GitOperationState =
  | "queued"
  | "preparing"
  | "committing"
  | "committed"
  | "verified"
  | "conflict"
  | "failed";

export type OutboxStatus = "pending" | "processing" | "done" | "failed";

export type WebhookDeliveryStatus = "received" | "processed" | "ignored" | "failed";

/**
 * Phase 5 contract §6 / design §14.5. `diverged` means the repository broke an
 * invariant Authorbot cannot reconcile deterministically (a chapter revision
 * moved backwards, or block ids referenced by live annotations vanished).
 * Prose writes are refused while diverged; reads are unaffected.
 */
export type ProjectStatus = "active" | "diverged";

export interface ProjectRecord {
  id: string;
  slug: string;
  repoProvider: string;
  /** Repository coordinates, e.g. `JoeMattie/causal-projector`. */
  repo: string;
  defaultBranch: string;
  /** {@link ProjectStatus} in practice; kept `string` so 0001-era rows widen. */
  status: string;
  /**
   * Phase 5 §6: a verified `push` marked the projection stale. Set BEFORE the
   * refresh is attempted and cleared only by one that finished, so a dropped
   * refresh is recoverable by the coordinator's periodic alarm.
   */
  projectionStale: boolean;
  /**
   * Repository commit the current projection was built from (design §20.3
   * "repository head versus projected head"). This is the *integrated* commit
   * against which a publication's `deployedCommit` is compared.
   */
  projectedCommit: string | null;
  /**
   * JSON detection record explaining `status = 'diverged'` (kind + offending
   * chapter/annotation ids), or the maintainer's clearing reason. Null when
   * the project has never diverged.
   */
  divergenceReason: unknown;
  /** When divergence was detected; null once cleared. */
  divergedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

/** CI build lifecycle as reported by the publisher (design §17.3). */
export type PublicationBuildStatus = "queued" | "building" | "succeeded" | "failed";

/**
 * Publication state per design §17.3. Written ONLY from signed CI callbacks -
 * never inferred from a successful Git commit. One row per integrated commit.
 */
export interface PublicationRecord {
  id: string;
  projectId: string;
  /** Repository commit CI built from. */
  integratedCommit: string;
  buildStatus: PublicationBuildStatus;
  /** Commit actually serving the public site, per CI. Null until deployed. */
  deployedCommit: string | null;
  publicUrl: string | null;
  deployedAt: string | null;
  publisherVersion: string | null;
  /** Delivery id of the callback that last advanced this row. */
  lastDeliveryId: string | null;
  createdAt: string;
  updatedAt: string;
}

export type PublicationDeliveryStatus = WebhookDeliveryStatus;

/** Dedupe ledger for signed `POST /v1/publications` callbacks (§6). */
export interface PublicationDeliveryRecord {
  id: string;
  projectId: string;
  deliveryId: string;
  publicationId: string | null;
  status: PublicationDeliveryStatus;
  receivedAt: string;
  processedAt: string | null;
}

export interface ActorRecord {
  id: string;
  type: ActorType;
  displayName: string;
  /** `<namespace>:<identifier>` per Phase 0 contract §2, e.g. `github:octocat`. */
  externalIdentity: string | null;
  ownerActorId: string | null;
  status: string;
  createdAt: string;
}

export interface ProjectMembershipRecord {
  id: string;
  projectId: string;
  actorId: string;
  role: MembershipRole;
  scopes: string[];
  createdAt: string;
  revokedAt: string | null;
}

export interface HumanSessionRecord {
  id: string;
  /** SHA-256 hash of the opaque session id. Plaintext is never stored. */
  sessionHash: string;
  actorId: string;
  createdAt: string;
  expiresAt: string;
  revokedAt: string | null;
}

/**
 * Which agent-token authorization representation is authoritative.
 *
 * `legacy` rows continue to use `scopes`; `canonical` rows use the additive
 * `capabilities_v2` column while retaining `scopes` as a rollback-safe shadow.
 */
export type AgentTokenCapabilityMode = "legacy" | "canonical";

export interface AgentTokenRecord {
  id: string;
  projectId: string;
  actorId: string;
  name: string;
  /** SHA-256 hash of the token. Plaintext is never stored. */
  tokenHash: string;
  scopes: string[];
  /**
   * Phase 11 canonical capability grants. NULL on an unconverted legacy row.
   *
   * Optional during the expand release so existing token constructors keep
   * producing legacy rows without a flag-day API change. Repository reads
   * always populate this field.
   */
  capabilitiesV2?: string[] | null;
  /**
   * The authoritative authorization representation. Optional inputs default
   * to `legacy`; repository reads always populate it.
   */
  capabilityMode?: AgentTokenCapabilityMode;
  createdBy: string;
  createdAt: string;
  expiresAt: string;
  revokedAt: string | null;
  lastUsedAt: string | null;
}

export interface ChapterProjectionRecord {
  id: string;
  projectId: string;
  path: string;
  slug: string;
  title: string;
  /** Current validated chapter-frontmatter summary, never public by itself. */
  summary: string | null;
  /** Frontmatter order; null only during migration before the next rebuild. */
  order: number | null;
  status: ChapterStatus;
  revision: number;
  contentHash: string;
  headCommit: string | null;
  lastPublishedCommit: string | null;
  /**
   * Valid block-marker ids of this projected revision. Persisted (contract
   * §4) so blockId-existence validation works from the database alone.
   */
  blockIds: string[];
  updatedAt: string;
}

/**
 * Unfiltered collaboration activity for one chapter-list row. The API applies
 * the caller's read capabilities before serializing these counts, so an
 * unauthorized category is omitted rather than exposed as a misleading zero.
 */
export interface ChapterActivitySummary {
  openSuggestions: number;
  openBlockComments: number;
  openChapterComments: number;
  /** Kept split so granular comment/suggestion reads can filter safely. */
  openCommentReplies: number;
  openSuggestionReplies: number;
  openWorkItems: number;
}

/** A chapter projection plus the activity aggregate loaded beside it. */
export interface ChapterSummaryRecord {
  chapter: ChapterProjectionRecord;
  activity: ChapterActivitySummary;
}

/** A cursor page with an explicit lookahead result. */
export interface ChapterSummaryPageRecord {
  items: ChapterSummaryRecord[];
  hasMore: boolean;
}

export interface AnnotationRecord {
  id: string;
  projectId: string;
  chapterId: string;
  kind: AnnotationKind;
  scope: AnnotationScope;
  chapterRevision: number;
  /** Target selector payload (design §10.1); null for chapter scope. */
  target: unknown;
  authorActorId: string;
  body: string;
  status: AnnotationRecordStatus;
  gitOperationId: string | null;
  supersededBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ReplyRecord {
  id: string;
  projectId: string;
  annotationId: string;
  parentReplyId: string | null;
  authorActorId: string;
  body: string;
  status: ReplyRecordStatus;
  gitOperationId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface GitOperationRecord {
  id: string;
  projectId: string;
  correlationId: string;
  expectedHead: string | null;
  state: GitOperationState;
  attempts: number;
  commitSha: string | null;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface OutboxRecord {
  id: string;
  projectId: string;
  gitOperationId: string | null;
  kind: string;
  payload: unknown;
  status: OutboxStatus;
  attempts: number;
  createdAt: string;
  processedAt: string | null;
}

export interface IdempotencyKeyRecord {
  id: string;
  projectId: string;
  actorId: string;
  key: string;
  requestHash: string;
  responseStatus: number | null;
  responseBody: string | null;
  createdAt: string;
}

export interface WebhookDeliveryRecord {
  id: string;
  deliveryId: string;
  event: string;
  status: WebhookDeliveryStatus;
  receivedAt: string;
  processedAt: string | null;
}

/** Phase 3 contract §2. */
export type VoteValue = "approve" | "reject" | "abstain";

/** Phase 0 contract §4 decision record `result`. */
export type DecisionResult =
  | "create_work_item"
  | "rejected"
  | "support_changed"
  | "overridden";

/** Phase 0 contract §4 work-item vocabulary (Phase 3 uses `revise_*` only). */
export type WorkItemType =
  | "revise_range"
  | "revise_block"
  | "revise_chapter"
  | "write_chapter"
  | "resolve_conflict"
  | "planning";

/** Phase 0 contract §4; Phase 3 stops at `ready` (Phase 3 contract §1). */
export type WorkItemStatus =
  | "ready"
  | "leased"
  | "submitted"
  | "applying"
  | "completed"
  | "conflict"
  | "failed"
  | "cancelled";

export type WorkItemPriority = "low" | "normal" | "high";

/** One current vote per (annotation, actor) - Phase 3 contract §2. */
export interface VoteRecord {
  id: string;
  projectId: string;
  annotationId: string;
  actorId: string;
  value: VoteValue;
  createdAt: string;
  updatedAt: string;
}

/**
 * Append-only vote history (Phase 3 contract §2). `value: null` records a
 * cleared vote; `previousValue: null` records a first vote.
 */
export interface VoteEventRecord {
  id: string;
  projectId: string;
  annotationId: string;
  actorId: string;
  value: VoteValue | null;
  previousValue: VoteValue | null;
  createdAt: string;
}

/**
 * Sticky decision record (Phase 3 contract §4, design §11.3-11.4). Unique on
 * `(sourceAnnotationId, actionType, ruleVersion)` - the idempotency key that
 * collapses concurrent threshold crossings to one decision. `ruleVersion` 0
 * is reserved for maintainer force-create.
 */
export interface DecisionRecord {
  id: string;
  projectId: string;
  sourceAnnotationId: string;
  actionType: string;
  rule: string;
  ruleVersion: number;
  /** Aggregate metrics snapshot at crossing - never per-voter data (§26.1). */
  metrics: Record<string, number>;
  result: DecisionResult;
  /** Design §11.3: set when support drops below the rule, cleared on return. */
  supportChanged: boolean;
  overrideReason: string | null;
  workItemId: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Phase 3 contract §4, design §13. */
export interface WorkItemRecord {
  id: string;
  projectId: string;
  type: WorkItemType;
  status: WorkItemStatus;
  sourceAnnotationId: string;
  chapterId: string;
  baseRevision: number;
  /** Annotation target selector snapshot incl. quote; null for chapter scope. */
  target: unknown;
  priority: WorkItemPriority;
  createdAt: string;
  updatedAt: string;
}

/**
 * A row of the SSE event feed (Phase 3 contract §5, design §15.5). `id` is a
 * database-assigned monotonic integer - the stream cursor.
 */
export interface EventRecord {
  id: number;
  projectId: string;
  type: string;
  payload: unknown;
  createdAt: string;
}

/** Input for appending an event; the database assigns the monotonic id. */
export type NewEventRecord = Omit<EventRecord, "id">;

/**
 * Phase 4 contract §2, design §12. Operational-only (never in Git; does not
 * survive a fresh-DB rebuild).
 *
 * Two distinct notions, defined in migration 0004:
 * - ACTIVE - `releasedAt === null && revokedAt === null`; the lease occupies
 *   its work item's single slot (partial-unique-index predicate).
 * - LIVE - active AND `expiresAt > now` at query time; only a live lease may
 *   renew or submit. Expired ⇔ `expiresAt <= now` (same boundary as
 *   human_sessions).
 *
 * `tokenHash` is the SHA-256 hex of the opaque lease token; each plaintext is
 * returned exactly once when issued at claim or credential-bound recovery,
 * and is never stored or logged.
 * Verification is a constant-time hash compare in the API layer.
 */
export interface LeaseRecord {
  id: string;
  projectId: string;
  workItemId: string;
  /** The holder. */
  actorId: string;
  /** SHA-256 hex of the lease token. Plaintext is never stored. */
  tokenHash: string;
  issuedAt: string;
  expiresAt: string;
  /** issuedAt + maximum total duration; renewals never extend past this. */
  maxExpiresAt: string;
  renewalCount: number;
  /** Voluntary release by holder or maintainer. */
  releasedAt: string | null;
  /** Involuntary end: lazy/swept expiry or administrative revocation. */
  revokedAt: string | null;
}

/** Phase 4 contract §1: the three Phase 4 submission types. */
export type SubmissionType =
  | "range_replacement"
  | "block_replacement"
  | "chapter_replacement";

/**
 * Phase 4 submission lifecycle: `received → applying → applied | conflicted`;
 * `rejected` records a post-insert verification failure.
 */
export type SubmissionState =
  | "received"
  | "applying"
  | "applied"
  | "conflicted"
  | "rejected";

/** Phase 4 contract §4, design §12.5. Content retained per contract §6. */
export interface SubmissionRecord {
  id: string;
  projectId: string;
  workItemId: string;
  leaseId: string;
  actorId: string;
  type: SubmissionType;
  baseRevision: number;
  /** `sha256:<hex>` of the chapter at baseRevision (task-bundle echo). */
  baseContentHash: string;
  content: string;
  summary: string | null;
  notes: string | null;
  state: SubmissionState;
  gitOperationId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface AuditEventRecord {
  id: string;
  projectId: string;
  actorId: string | null;
  action: string;
  targetType: string;
  targetId: string | null;
  correlationId: string;
  /** Safe metadata only - never token/session material (design §20.6). */
  metadata: unknown;
  createdAt: string;
}

/**
 * Projected `book.yml` for a project (Phase 6 contract §3.6, migration 0006).
 * `config` is the parsed `authorbot.book/v1` document; the database layer
 * keeps it `unknown` and leaves validation to `@authorbot/schemas` at the
 * boundary, exactly as `AuditEventRecord.metadata` does.
 */
export interface BookConfigRecord {
  projectId: string;
  config: unknown;
  status: BookConfigStatus;
  gitOperationId: string | null;
  sourceCommit: string | null;
  createdAt: string;
  updatedAt: string;
}

/** `pending_git` until the outbox commits `book.yml`; then `committed`. */
export type BookConfigStatus = "pending_git" | "committed";

// ---------------------------------------------------------------------------
// Phase 7: author-facing access control (migration 0007)
// ---------------------------------------------------------------------------

/**
 * The emergency stops for one project (Phase 7 contract "Restricting").
 *
 * Both controls are represented as a nullable timestamp rather than a boolean:
 * "frozen since 14:02, by Avery, because the fleet went haywire" is what an
 * author needs to read an hour later, and a boolean would have thrown all of it
 * away. A NULL `*_at` means the control is not in effect, and the actor/reason
 * columns beside it are NULL too.
 */
export interface ProjectAccessControlRecord {
  projectId: string;
  frozenAt: string | null;
  frozenByActorId: string | null;
  freezeReason: string | null;
  agentsPausedAt: string | null;
  agentsPausedByActorId: string | null;
  agentsPauseReason: string | null;
  createdAt: string;
  updatedAt: string;
}

export type PendingAnnotationStatus = "pending" | "approved" | "rejected";

/**
 * A queued annotation awaiting a maintainer's approval (Phase 7 contract
 * "Moderating"). Structurally NOT an `AnnotationRecord`: it lives in its own
 * table precisely so that it cannot be voted on, cannot be evaluated by the
 * rule engine, and has no git operation to be committed by.
 */
export interface PendingAnnotationRecord {
  id: string;
  projectId: string;
  chapterId: string;
  kind: "comment" | "suggestion";
  scope: "range" | "block" | "chapter";
  chapterRevision: number;
  target: unknown;
  authorActorId: string;
  body: string;
  status: PendingAnnotationStatus;
  reviewedByActorId: string | null;
  reviewedAt: string | null;
  rejectionReason: string | null;
  /** The `annotations.id` an approval created (equal to `id`). */
  approvedAnnotationId: string | null;
  createdAt: string;
  updatedAt: string;
}

/** One fixed rate-limit window for one subject and class (migration 0007). */
export interface RateLimitCounterRecord {
  subject: string;
  class: string;
  windowStart: string;
  count: number;
  expiresAt: string;
}

// ---------------------------------------------------------------------------
// Phase 11: review-gated chapter and summary revisions (migration 0011)
// ---------------------------------------------------------------------------

/** Exact chapter source delivered in a whole-chapter lease task bundle. */
export interface LeaseDocumentSnapshotRecord {
  leaseId: string;
  projectId: string;
  chapterId: string;
  baseRevision: number;
  baseContentHash: string;
  source: string;
  createdAt: string;
}

/** The content surface replaced by a revision proposal. */
export type RevisionProposalType =
  | "chapter_replacement"
  | "chapter_summary"
  | "repository_document";

/** Canonical repository surface addressed by a proposal. */
export type RevisionProposalTargetKind = "chapter" | "outline" | "timeline" | "character";

/** How a proposal entered the shared maintainer-review pipeline. */
export type RevisionProposalOrigin =
  | "work_submission"
  | "direct_edit"
  | "summary_proposal"
  | "history_restore"
  | "document_edit";

/**
 * A proposal begins pending review, may be applied through the Git outbox,
 * and finishes in one of the four terminal states. The repository guards
 * every transition with the expected current status so concurrent reviewers
 * cannot act on the same proposal twice.
 */
export type RevisionProposalStatus =
  | "pending_review"
  | "applying"
  | "approved"
  | "rejected"
  | "conflicted"
  | "withdrawn";

/**
 * Immutable proposal payload plus its mutable review/apply envelope.
 *
 * `baseContent` is deliberately retained beside `proposedContent`: review
 * pages can render an exact diff without fetching an old Git tree once per
 * proposal. Migration 0011 prevents either snapshot, its authorship, or its
 * work/submission identity from changing after insertion.
 */
export interface RevisionProposalRecord {
  id: string;
  projectId: string;
  chapterId: string | null;
  targetKind: RevisionProposalTargetKind;
  /** Chapter UUID, `outline`, `timeline`, or the character's canonical id. */
  targetId: string;
  /** Exact repository-relative file compared and eventually written. */
  targetPath: string;
  proposalType: RevisionProposalType;
  origin: RevisionProposalOrigin;
  workItemId: string | null;
  submissionId: string | null;
  authorActorId: string;
  /** Null for repository planning documents, which use `baseContentHash`. */
  baseRevision: number | null;
  baseContentHash: string;
  baseContent: string;
  proposedContent: string;
  changeSummary: string | null;
  notes: string | null;
  status: RevisionProposalStatus;
  reviewedByActorId: string | null;
  reviewedAt: string | null;
  reviewReason: string | null;
  gitOperationId: string | null;
  resultingRevision: number | null;
  commitSha: string | null;
  createdAt: string;
  updatedAt: string;
}
